CREATE FUNCTION ROUNDABNT(AVALOR NUMERIC,ADECIMAIS INTEGER) RETURNS DOUBLE PRECISION AS $$
DECLARE
POW NUMERIC; 
FRACVALUE NUMERIC; 
POWVALUE NUMERIC;
RESTPART NUMERIC;
VDELTA NUMERIC;
INTCALC BIGINT; 
FRACCALC BIGINT; 
LASTNUMBER BIGINT; 
INTVALUE BIGINT; 
FRACINTCALC NUMERIC; 
FRACPOWVALUE NUMERIC;
BEGIN
    POW       = POWER(10, ABS(ADECIMAIS) );
    POWVALUE  = ABS(AVALOR) / 10 ;
    INTVALUE  = TRUNC(POWVALUE);
    FRACVALUE = POWVALUE -INTVALUE;
    VDELTA = (1*(POWER(10,-5)));

   POWVALUE = ROUND( FRACVALUE * 10 * POW, 9);
   INTCALC  = TRUNC( POWVALUE );
   FRACCALC = TRUNC( (POWVALUE-INTCALC) * 100 );        

   IF (FRACCALC > 50) THEN
     INTCALC = INTCALC + 1;   
   ELSE 
       IF (FRACCALC = 50) THEN
       BEGIN
         FRACINTCALC = (INTCALC/10)-TRUNC((INTCALC/10));
         LASTNUMBER = ROUND(FRACINTCALC * 10);
    
            IF (MOD(LASTNUMBER,2) <> 0) THEN
                INTCALC = INTCALC + 1; 
            ELSE
                BEGIN
                FRACPOWVALUE = (POWVALUE*10)-TRUNC((POWVALUE*10));
                RESTPART = FRACPOWVALUE ;
    
                IF RESTPART > VDELTA THEN
                    INTCALC = INTCALC + 1; 
                END IF;
                END;
            END IF;
       END;
       END IF;
   END IF;

   IF (AVALOR < 0) THEN
     RETURN (-1*((INTVALUE*10) + (INTCALC / POW)));
   ELSE
    RETURN ((INTVALUE*10) + (INTCALC / POW));
   END IF;
END;$$ 
LANGUAGE PLPGSQL;